import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Award, BrainCircuit, Check, CircleDot, CloudCog, Code2, Database, Github, Linkedin, Mail, MapPin, Network, Terminal, Trophy } from "lucide-react";
import * as Tabs from "@radix-ui/react-tabs";
import { Button } from "@/components/ui/button";
import { coreStack, focusAreas, journey, profile, projects, skillGroups, stats } from "@/data/portfolio";
import { ContactForm } from "./contact-form";
import { Navigation } from "./navigation";
import { ProjectCard } from "./project-card";
import { SectionHeading, SocialLinks, TechBadge } from "./primitives";
import { usePortfolioMotion } from "@/hooks/use-portfolio-motion";

function AnimatedStat({ value, suffix, label }: (typeof stats)[number]) {
  const ref = useRef<HTMLDivElement>(null); const [count, setCount] = useState(0);
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (!entry?.isIntersecting) return; if (matchMedia("(prefers-reduced-motion: reduce)").matches) setCount(value); else { const start = performance.now(); const tick = (now: number) => { const p = Math.min((now - start) / 900, 1); setCount(Math.round(value * (1 - Math.pow(1 - p, 3)))); if (p < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); } observer.disconnect(); }, { threshold: .5 }); observer.observe(node); return () => observer.disconnect(); }, [value]);
  return <div ref={ref} className="min-w-0 border-l border-border px-4 first:border-l-0 sm:px-6"><p className="font-mono text-xl font-semibold text-foreground sm:text-2xl">{count}{suffix}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>;
}

const philosophies = [
  ["01", "Understand", "Start with the problem, users, constraints, and desired outcome."],
  ["02", "Design", "Think about architecture, data flow, APIs, maintainability, and scalability."],
  ["03", "Build", "Turn ideas into clean, tested, production-oriented software."],
  ["04", "Improve", "Measure, debug, iterate, and continuously learn."],
];
const achievements = [
  [Trophy, "500+ DSA Problems Solved", "Consistent practice across core data structures and algorithms."],
  [Code2, "7+ End-to-End Projects", "Products built across frontend, backend, data, deployment, and AI."],
  [BrainCircuit, "AI & LLM Applications", "Practical assistants and workflows powered by language models."],
  [Network, "RAG & Vector Search Systems", "Document retrieval, embeddings, graphs, and semantic search."],
  [CloudCog, "CI/CD & Cloud Deployment", "Containerized delivery pipelines and cloud deployment workflows."],
  [Award, "Continuous Learning", "A steady progression from fundamentals to production-oriented systems."],
] as const;

export function PortfolioPage() {
  const motionRef = usePortfolioMotion();
  return <div ref={motionRef} id="top" className="portfolio-motion min-h-screen overflow-x-hidden bg-background text-foreground"><Navigation />
    <main>
      <section className="relative mx-auto grid min-h-[min(900px,92vh)] max-w-7xl items-center gap-12 px-4 pb-14 pt-28 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:pt-24">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground"><span className="size-2 rounded-full bg-success shadow-status" />Open to Software Engineering Opportunities</div><p className="mt-7 text-sm font-medium text-muted-foreground">Full-Stack Developer · AI & LLM Engineer</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.08] tracking-tight text-foreground sm:text-6xl lg:text-7xl">Building thoughtful software with <span className="text-accent-strong">Full-Stack Engineering & AI.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Computer Science engineer focused on building scalable web applications, AI-powered products, RAG systems, and practical machine learning solutions.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href="#projects">View Projects <ArrowDown className="size-4" /></a></Button><Button asChild variant="outline"><a href="/resume.pdf" download="Suraj_Kumar_Gupta_Resume.pdf">Download Resume</a></Button></div><SocialLinks labels className="mt-5 -ml-3" /></div>
        <div className="relative mx-auto w-full max-w-xl lg:max-w-none"><div className="code-window overflow-hidden rounded-lg border border-border bg-code shadow-panel"><div className="flex h-11 items-center gap-2 border-b border-code-border px-4"><span className="size-2.5 rounded-full bg-code-dot" /><span className="size-2.5 rounded-full bg-code-dot" /><span className="size-2.5 rounded-full bg-code-dot" /><span className="ml-3 font-mono text-[11px] text-code-muted">developer.ts</span></div><div className="grid grid-cols-[2.5rem_1fr] px-3 py-6 font-mono text-xs leading-7 sm:px-5 sm:text-sm"><div className="select-none text-right text-code-muted">1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7</div><pre className="ml-5 overflow-x-auto text-code-text"><code><span className="text-code-key">const</span> developer = {`{`}<br/>  focus: [<span className="text-code-string">"Full-Stack"</span>, <span className="text-code-string">"AI"</span>, <span className="text-code-string">"LLMs"</span>],<br/>  building: <span className="text-code-string">"useful software"</span>,<br/>  mindset: <span className="text-code-string">"learn → build → improve"</span>,<br/>  available: <span className="text-code-bool">true</span><br/>{`}`};<br/><span className="text-code-comment">// ship with intent.</span></code></pre></div><div className="flex items-center gap-2 border-t border-code-border px-4 py-3 font-mono text-[11px] text-code-muted"><Terminal className="size-3.5" />TypeScript · production mindset</div></div></div>
      </section>
      <div className="border-y border-border bg-section"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-6 px-4 py-6 sm:px-6 md:grid-cols-5 lg:px-8">{stats.map((stat) => <AnimatedStat key={stat.label} {...stat} />)}</div></div>

      <section id="about" className="scroll-mt-20 py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="About" title="A little about me" /><div className="mt-12 grid gap-12 lg:grid-cols-2 lg:gap-20"><div><p className="text-xl leading-8 text-foreground">{profile.intro}</p><p className="mt-6 leading-7 text-muted-foreground">My strongest work sits where product engineering and intelligent systems meet: building reliable interfaces, APIs, data flows, retrieval pipelines, and deployment workflows that solve real problems.</p><div className="mt-8 flex flex-wrap gap-2">{coreStack.map((tech) => <TechBadge key={tech}>{tech}</TechBadge>)}</div></div><div className="border-l border-border pl-6 sm:pl-10"><p className="text-sm font-semibold">Currently focused on</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{focusAreas.map((area) => <div key={area} className="flex items-center gap-3 border-b border-border py-3 text-sm text-muted-foreground"><Check className="size-4 text-accent-strong" />{area}</div>)}</div></div></div></div></section>

      <section id="projects" className="scroll-mt-20 border-y border-border bg-section py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Selected Work" title="Systems built beyond the tutorial." description="Projects where I explored real-world product engineering, AI systems, and scalable architecture." /><div className="mt-12 grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((project, index) => <ProjectCard key={project.name} project={project} index={index} />)}</div></div></section>

      <section id="skills" className="scroll-mt-20 py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Capabilities" title="Technical Expertise" description="A practical toolkit spanning product interfaces, backend systems, data, AI, and delivery." /><Tabs.Root defaultValue="Frontend" className="mt-12"><Tabs.List className="flex overflow-x-auto border-b border-border" aria-label="Technical skill categories">{skillGroups.map((group) => <Tabs.Trigger key={group.name} value={group.name} className="shrink-0 border-b-2 border-transparent px-4 py-3 text-sm font-medium text-muted-foreground data-[state=active]:border-accent-strong data-[state=active]:text-foreground">{group.name}</Tabs.Trigger>)}</Tabs.List>{skillGroups.map((group) => <Tabs.Content key={group.name} value={group.name} className="mt-8 rounded-lg border border-border bg-card p-6 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:p-8"><div className="grid gap-6 md:grid-cols-[.45fr_1fr]"><div><p className="font-mono text-xs text-accent-strong">EXPERTISE / {group.name.toUpperCase()}</p><h3 className="mt-3 text-2xl font-semibold">{group.name}</h3></div><div className="flex flex-wrap content-start gap-2">{group.skills.map((skill) => <span key={skill} className="rounded-md border border-border bg-secondary px-3 py-2 text-sm text-secondary-foreground">{skill}</span>)}</div></div></Tabs.Content>)}</Tabs.Root></div></section>

      <section className="border-y border-border bg-section py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Process" title="How I Build" /><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{philosophies.map(([number, title, text]) => <article key={number} className="bg-card p-6 sm:p-7"><span className="font-mono text-xs text-accent-strong">{number}</span><h3 className="mt-12 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>

      <section id="journey" className="scroll-mt-20 py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-4 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><SectionHeading eyebrow="Journey" title="Built one layer at a time." description="A progression from programming fundamentals to full-stack products and AI-powered systems." /><ol className="relative border-l border-border">{journey.map((item) => <li key={`${item.year}-${item.title}`} className="relative pb-10 pl-8 last:pb-0"><span className={`absolute -left-[7px] top-1 size-3 rounded-full border-2 border-background ${item.current ? "bg-success shadow-status" : "bg-muted-foreground"}`} /><div className="grid gap-2 sm:grid-cols-[7rem_1fr]"><time className={`font-mono text-xs ${item.current ? "text-success" : "text-muted-foreground"}`}>{item.year}</time><div><h3 className="font-semibold text-foreground">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.description}</p>{item.current && <span className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-success/30 px-2 py-1 text-[11px] font-medium text-success"><CircleDot className="size-3" />Current focus</span>}</div></div></li>)}</ol></div></section>

      <section id="achievements" className="scroll-mt-20 border-y border-border bg-section py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Evidence" title="Achievements" description="Concrete progress across problem solving, product engineering, AI systems, and delivery." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{achievements.map(([Icon, title, description]) => <article key={title} className="rounded-lg border border-border bg-card p-6"><Icon className="size-5 text-accent-strong" /><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>)}</div></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Developer Presence" title="Build in Public" description="Code, problem solving, and professional updates—shared on the platforms where I learn and build." /><div className="overflow-hidden rounded-lg border border-border bg-code shadow-panel"><div className="flex items-center justify-between border-b border-code-border px-5 py-4"><div className="flex items-center gap-2 text-sm font-medium text-code-text"><Github className="size-4" />Surajgupta001</div><a href={profile.links.github} target="_blank" rel="noreferrer" className="text-xs text-code-muted hover:text-code-text">View profile <ArrowUpRight className="ml-1 inline size-3" /></a></div><div className="space-y-0 px-5">{[["gocart", "Full-stack product"], ["JARVIS", "AI assistant"], ["rag-chatbot", "Document intelligence"], ["HYBRID-RAG", "Hybrid retrieval"]].map(([repo, summary]) => <div key={repo} className="flex items-center justify-between border-b border-code-border py-4 last:border-0"><div className="min-w-0"><p className="truncate font-mono text-sm text-code-text">{repo}</p><p className="mt-1 text-xs text-code-muted">{summary}</p></div><span className="ml-4 size-2 shrink-0 rounded-full bg-accent-strong" /></div>)}</div></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[{ icon: Github, label: "GitHub", text: "Explore repositories", href: profile.links.github }, { icon: Linkedin, label: "LinkedIn", text: "Connect professionally", href: profile.links.linkedin }, { icon: Code2, label: "LeetCode", text: "View problem solving", href: profile.links.leetcode }].map(({ icon: Icon, label, text, href }) => <a key={label} href={href} target="_blank" rel="noreferrer" className="group flex items-center gap-4 rounded-lg border border-border bg-card p-5 transition hover:border-strong"><Icon className="size-5 text-accent-strong" /><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{text}</p></div><ArrowRight className="ml-auto size-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></a>)}</div></div></section>

      <section id="contact" className="scroll-mt-20 border-t border-border bg-section py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><SectionHeading eyebrow="Contact" title="Let’s build something useful." description="Have a project, opportunity, or idea worth exploring? I’d be happy to hear about it." /><div className="mt-8 space-y-4 text-sm text-muted-foreground"><a href={`mailto:${profile.email}`} className="flex items-center gap-3 hover:text-foreground"><Mail className="size-4 text-accent-strong" />{profile.email}</a><p className="flex items-center gap-3"><MapPin className="size-4 text-accent-strong" />{profile.location}</p></div></div><ContactForm /></div></section>
    </main>
    <footer className="border-t border-border py-8"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div><p className="text-sm text-foreground">© 2026 Suraj Kumar Gupta</p><p className="mt-1 text-xs text-muted-foreground">Built with React + shadcn/ui</p></div><SocialLinks labels /></div></footer>
  </div>;
}
