import * as Dialog from "@radix-ui/react-dialog";
import { ArrowUpRight, Github, X } from "lucide-react";
import type { Project } from "@/data/portfolio";
import { Button } from "@/components/ui/button";
import { TechBadge } from "./primitives";

export function ProjectCard({ project, index }: { project: Project; index: number }) {
  return <Dialog.Root><article className="group flex h-full flex-col rounded-lg border border-border bg-card p-6 shadow-card transition duration-300 hover:-translate-y-1 hover:border-strong hover:shadow-card-hover">
    <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase text-accent-strong">{project.category}</p><h3 className="mt-3 text-xl font-semibold text-card-foreground">{project.name}</h3></div><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span></div>
    <p className="mt-4 flex-1 text-sm leading-6 text-muted-foreground">{project.description}</p>
    <div className="mt-5 flex flex-wrap gap-1.5">{project.technologies.slice(0, 5).map((tech) => <TechBadge key={tech}>{tech}</TechBadge>)}{project.technologies.length > 5 && <TechBadge>{`+${project.technologies.length - 5}`}</TechBadge>}</div>
    <div className="mt-6 flex items-center justify-between border-t border-border pt-4"><Dialog.Trigger asChild><Button variant="ghost" className="-ml-3">Case study <ArrowUpRight className="size-4" /></Button></Dialog.Trigger><div className="flex gap-1"><Button asChild variant="ghost" size="icon"><a href={project.github} target="_blank" rel="noreferrer" aria-label={`${project.name} on GitHub`}><Github className="size-4" /></a></Button>{project.live && <Button asChild variant="ghost" size="icon"><a href={project.live} target="_blank" rel="noreferrer" aria-label={`${project.name} live demo`}><ArrowUpRight className="size-4" /></a></Button>}</div></div>
  </article><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[60] bg-overlay/75 backdrop-blur-sm" /><Dialog.Content className="fixed left-1/2 top-1/2 z-[61] max-h-[88vh] w-[calc(100%-2rem)] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-lg border border-border bg-background p-6 shadow-2xl sm:p-8"><div className="pr-10"><p className="eyebrow">{project.category}</p><Dialog.Title className="mt-3 text-2xl font-semibold text-foreground sm:text-3xl">{project.name}</Dialog.Title><Dialog.Description className="mt-3 leading-7 text-muted-foreground">{project.description}</Dialog.Description></div><Dialog.Close asChild><Button variant="ghost" size="icon" className="absolute right-4 top-4" aria-label="Close project details"><X className="size-5" /></Button></Dialog.Close><div className="mt-8 grid gap-7 sm:grid-cols-2"><Detail title="Problem" text={project.problem} /><Detail title="Solution" text={project.solution} /><div><h4 className="text-sm font-semibold text-foreground">Key features</h4><ul className="mt-3 space-y-2 text-sm leading-6 text-muted-foreground">{project.features.map((feature) => <li key={feature} className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-accent-strong" />{feature}</li>)}</ul></div><Detail title="Engineering considerations" text={project.engineering} /></div><div className="mt-7 border-t border-border pt-6"><h4 className="text-sm font-semibold">Technology stack</h4><div className="mt-3 flex flex-wrap gap-2">{project.technologies.map((tech) => <TechBadge key={tech}>{tech}</TechBadge>)}</div><div className="mt-6 flex flex-wrap gap-3"><Button asChild><a href={project.github} target="_blank" rel="noreferrer"><Github className="size-4" />View repository</a></Button>{project.live && <Button asChild variant="outline"><a href={project.live} target="_blank" rel="noreferrer">Live demo <ArrowUpRight className="size-4" /></a></Button>}</div></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function Detail({ title, text }: { title: string; text: string }) { return <div><h4 className="text-sm font-semibold text-foreground">{title}</h4><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
